kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: sfc-ldap-service
data:
  application.properties: |
    # Override the configuration properties here
    ldap.server.ip=ldap://172.29.120.112:389